version: '3.4'

services:
  webapplication1:
    container_name: web
    image: ${DOCKER_REGISTRY-}webapplication1
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile
    depends_on:
      - 'postgresCompose'
    networks: 
      - superCoolNet
    ports:
      - "80:80"


  postgresCompose:
    container_name: 'postgresCompose'
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - "./WebApplication1/tables.sql:/docker-entrypoint-initdb.d/tables.sql"
    networks: 
      - superCoolNet
    ports:
      - "5432:5432"


networks: 
  superCoolNet:
    driver: bridge

